[project]
name = "agentic-framework"
version = "0.0.1"
description = "Exploration of Agentic Frameworks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "smolagents>=1.0.0",
    "sqlalchemy>=2.0.36",
]
